name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container registry
      uses: docker/login-action@v1
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GHCR_PASSWORD }}
      with:
        registry: ghcr.io
        username: $GITHUB_USER
        password: ${{ secrets.GHCR_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
          push: true
          tags: ${{ github.repository_owner }}/app:latest